"use client";

import { Plus, Settings2, Trash2 } from "lucide-react";
import { useBuilder } from "./BuilderContext";
import { ImageField } from "./ImageField";
import { MODULE_META, Product, Seller, StoreModule, Tile, uid } from "./types";

const Field = ({ label, value, onChange, type = "text", min, max }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; min?: number; max?: number }) => <div><label className="field-label">{label}</label><input className="field-input" type={type} min={min} max={max} value={value} onChange={(e) => onChange(e.target.value)} /></div>;
const Area = ({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) => <div><label className="field-label">{label}</label><textarea className="field-input min-h-24 resize-y" value={value} onChange={(e) => onChange(e.target.value)} /></div>;
const Select = ({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) => <div><label className="field-label">{label}</label><select className="field-input" value={value} onChange={(e) => onChange(e.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>;
const AddButton = ({ children, onClick, disabled }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) => <button disabled={disabled} onClick={onClick} className="flex h-8 w-full items-center justify-center gap-1.5 rounded border border-dashed border-slate-300 text-xs font-semibold text-slate-600 transition hover:border-slate-400 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40"><Plus size={13} />{children}</button>;

function ItemHeader({ title, onRemove, disabled = false }: { title: string; onRemove: () => void; disabled?: boolean }) { return <div className="flex items-center justify-between"><span className="text-[11px] font-bold text-slate-500">{title}</span><button disabled={disabled} className="icon-button h-6 w-6 text-red-500" onClick={onRemove} title={disabled ? "商品网格至少保留 2 个商品" : "删除项目"}><Trash2 size={12} /></button></div>; }

function ProductEditor({ product, onChange, onRemove, index, removeDisabled = false, imageRecommended = "1500 × 1500 px" }: { product: Product; onChange: (product: Product) => void; onRemove: () => void; index: number; removeDisabled?: boolean; imageRecommended?: string }) {
  return <div className="item-box"><ItemHeader title={`商品 ${index + 1}`} onRemove={onRemove} disabled={removeDisabled} /><ImageField label="商品图片" value={product.image} onChange={(image) => onChange({ ...product, image })} recommended={imageRecommended} /><Field label="商品名称" value={product.name} onChange={(name) => onChange({ ...product, name })} /><Field label="价格" value={product.price} onChange={(price) => onChange({ ...product, price })} /><Field label="ASIN" value={product.asin} onChange={(asin) => onChange({ ...product, asin })} /></div>;
}

function Editors({ module, update }: { module: StoreModule; update: (patch: Partial<StoreModule>) => void }) {
  const updateProduct = (products: Product[], index: number, product: Product, key: "products") => update({ [key]: products.map((p, i) => i === index ? product : p) } as Partial<StoreModule>);
  const productList = (products: Product[], options?: { min?: number; imageRecommended?: string }) => { const min = options?.min ?? 0; return <>{products.map((product, i) => <ProductEditor key={product.id} product={product} index={i} imageRecommended={options?.imageRecommended} removeDisabled={products.length <= min} onChange={(next) => updateProduct(products, i, next, "products")} onRemove={() => update({ products: products.filter((_, n) => n !== i) } as Partial<StoreModule>)} />)}<AddButton onClick={() => update({ products: [...products, { id: uid(), image: "", name: "新商品", price: "¥0", asin: "" }] } as Partial<StoreModule>)}>添加商品</AddButton></>; };
  switch (module.type) {
    case "header": return <><ImageField label="桌面端图片" value={module.desktopImage} onChange={(desktopImage) => update({ desktopImage })} recommended="3000 × 600 px" /><ImageField label="移动端图片" value={module.mobileImage} onChange={(mobileImage) => update({ mobileImage })} recommended="750 × 750 px" /><Field label="标题" value={module.title} onChange={(title) => update({ title })} /><Area label="副标题" value={module.subtitle} onChange={(subtitle) => update({ subtitle })} /><Field label="按钮文字" value={module.buttonText} onChange={(buttonText) => update({ buttonText })} /><Field label="按钮链接" value={module.buttonLink} onChange={(buttonLink) => update({ buttonLink })} /></>;
    case "heroVideo": return <><Field label="桌面端视频 URL 或 YouTube 链接" value={module.videoUrl} onChange={(videoUrl) => update({ videoUrl })} /><p className="field-help">推荐尺寸：3000 × 600 px。画布中以视频背景占位方式展示。</p><ImageField label="移动端备用图" value={module.mobileImage} onChange={(mobileImage) => update({ mobileImage })} recommended="750 × 750 px" /><Field label="标题" value={module.title} onChange={(title) => update({ title })} /><Area label="副标题" value={module.subtitle} onChange={(subtitle) => update({ subtitle })} /><Field label="按钮文字" value={module.buttonText} onChange={(buttonText) => update({ buttonText })} /></>;
    case "logo": return <><ImageField label="标志图片" value={module.image} onChange={(image) => update({ image })} recommended="600 × 600 px" /><Field label="替代文字" value={module.alt} onChange={(alt) => update({ alt })} /></>;
    case "gallery": return <>{module.images.map((item, i) => <div className="item-box" key={item.id}><ItemHeader title={`幻灯片 ${i + 1}`} onRemove={() => update({ images: module.images.filter((_, n) => n !== i) })} /><ImageField label="图片" value={item.image} onChange={(image) => update({ images: module.images.map((x, n) => n === i ? { ...x, image } : x) })} recommended="1500 × 1500 px" /><Field label="替代文字" value={item.alt} onChange={(alt) => update({ images: module.images.map((x, n) => n === i ? { ...x, alt } : x) })} /></div>)}<AddButton disabled={module.images.length >= 8} onClick={() => update({ images: [...module.images, { id: uid(), image: "", alt: `画廊图片 ${module.images.length + 1}` }] })}>添加图片 ({module.images.length}/8)</AddButton></>;
    case "shoppable": return <><ImageField label="背景图片" value={module.image} onChange={(image) => update({ image })} recommended="1500 × 1500 px" />{module.hotspots.map((spot, i) => <div className="item-box" key={spot.id}><ItemHeader title={`热点 ${i + 1}`} onRemove={() => update({ hotspots: module.hotspots.filter((_, n) => n !== i) })} /><div className="grid grid-cols-2 gap-2"><Field label="横向位置 (%)" type="number" min={0} max={100} value={spot.x} onChange={(x) => update({ hotspots: module.hotspots.map((s, n) => n === i ? { ...s, x: Math.max(0, Math.min(100, Number(x))) } : s) })} /><Field label="纵向位置 (%)" type="number" min={0} max={100} value={spot.y} onChange={(y) => update({ hotspots: module.hotspots.map((s, n) => n === i ? { ...s, y: Math.max(0, Math.min(100, Number(y))) } : s) })} /></div><Field label="ASIN" value={spot.asin} onChange={(asin) => update({ hotspots: module.hotspots.map((s, n) => n === i ? { ...s, asin } : s) })} /></div>)}<AddButton onClick={() => update({ hotspots: [...module.hotspots, { id: uid(), x: 50, y: 50, asin: "" }] })}>添加热点</AddButton></>;
    case "productGrid": return <><Field label="每行商品数" type="number" min={2} max={5} value={Math.min(module.columns, 5)} onChange={(columns) => update({ columns: Math.max(2, Math.min(5, Number(columns))) })} /><p className="field-help">每行最多展示 5 个商品；继续添加商品时会自动换行。</p>{productList(module.products, { min: 2, imageRecommended: "2000 × 2000 px（至少 1000 × 1000 px）" })}</>;
    case "collection": return <><ImageField label="合集封面" value={module.cover} onChange={(cover) => update({ cover })} recommended="1500 × 1500 px" /><Field label="标题" value={module.title} onChange={(title) => update({ title })} />{productList(module.products)}</>;
    case "bestSellers":
    case "featuredDeals": return <><Field label="区块标题" value={module.title} onChange={(title) => update({ title })} />{module.type === "featuredDeals" && <Field label="促销角标文字（可选）" value={module.badgeText} onChange={(badgeText) => update({ badgeText })} />}{module.products.map((product, i) => <div className="item-box" key={product.id}><ItemHeader title={`${module.type === "featuredDeals" ? "优惠商品" : "热销商品"} ${i + 1}`} onRemove={() => update({ products: module.products.filter((_, n) => n !== i) })} /><Field label="商品名称" value={product.name} onChange={(name) => update({ products: module.products.map((p, n) => n === i ? { ...p, name } : p) })} /><Field label="价格" value={product.price} onChange={(price) => update({ products: module.products.map((p, n) => n === i ? { ...p, price } : p) })} /><Field label="星级" type="number" min={1} max={5} value={product.stars} onChange={(stars) => update({ products: module.products.map((p, n) => n === i ? { ...p, stars: Math.max(1, Math.min(5, Number(stars))) } : p) })} /><Field label="ASIN" value={product.asin} onChange={(asin) => update({ products: module.products.map((p, n) => n === i ? { ...p, asin } : p) })} /></div>)}<AddButton onClick={() => update({ products: [...module.products, { id: uid(), name: "新品", price: "¥0", stars: 5, asin: "" } as Seller] })}>添加商品</AddButton></>;
    case "video": return <><Field label="YouTube 链接" value={module.url} onChange={(url) => update({ url })} /><Field label="视频标题" value={module.title} onChange={(title) => update({ title })} /><p className="field-help">视频预览使用 16:9 画面比例。</p></>;
    case "text": return <><Field label="标题" value={module.title} onChange={(title) => update({ title })} /><Area label="正文" value={module.body} onChange={(body) => update({ body })} /></>;
    case "imageWithText": return <><ImageField label="图片" value={module.image} onChange={(image) => update({ image })} recommended="1500 × 1500 px" /><Field label="标题" value={module.title} onChange={(title) => update({ title })} /><Area label="正文" value={module.body} onChange={(body) => update({ body })} /><Field label="按钮文字" value={module.buttonText} onChange={(buttonText) => update({ buttonText })} /><Select label="布局方向" value={module.layout} onChange={(layout) => update({ layout: layout as "left" | "right" })} options={[{ value: "left", label: "图片在左" }, { value: "right", label: "图片在右" }]} /></>;
    case "testimonial": return <><ImageField label="头像" value={module.avatar} onChange={(avatar) => update({ avatar })} recommended="300 × 300 px" /><Field label="姓名" value={module.name} onChange={(name) => update({ name })} /><Area label="评价内容" value={module.text} onChange={(text) => update({ text })} /></>;
    case "categoryTiles": return <><Field label="列数" type="number" min={2} max={4} value={module.columns} onChange={(columns) => update({ columns: Math.max(2, Math.min(4, Number(columns))) })} />{module.tiles.map((tile, i) => <div className="item-box" key={tile.id}><ItemHeader title={`分类 ${i + 1}`} onRemove={() => update({ tiles: module.tiles.filter((_, n) => n !== i) })} /><ImageField label="分类图片" value={tile.image} onChange={(image) => update({ tiles: module.tiles.map((t, n) => n === i ? { ...t, image } : t) })} recommended="1500 × 1500 px" /><Field label="名称" value={tile.name} onChange={(name) => update({ tiles: module.tiles.map((t, n) => n === i ? { ...t, name } : t) })} /><Field label="链接" value={tile.link} onChange={(link) => update({ tiles: module.tiles.map((t, n) => n === i ? { ...t, link } : t) })} /></div>)}<AddButton onClick={() => update({ tiles: [...module.tiles, { id: uid(), image: "", name: "新分类", link: "#" } as Tile] })}>添加分类</AddButton></>;
  }
}

function StoreIdentity() {
  const { storeSettings, updateStoreSettings } = useBuilder();
  return <section className="space-y-3"><div><p className="panel-title">店铺信息</p><p className="mt-1 text-xs leading-5 text-slate-400">显示在横幅下方的全局导航栏，所有页面共用。</p></div><ImageField label="店铺图标" value={storeSettings.logo} onChange={(logo) => updateStoreSettings({ logo })} recommended="600 × 600 px" /><Field label="店铺名称" value={storeSettings.brandName} onChange={(brandName) => updateStoreSettings({ brandName })} /><Field label="关注按钮文字" value={storeSettings.followText} onChange={(followText) => updateStoreSettings({ followText })} /></section>;
}

function PageNavigation() {
  const { pages, activePageId, selectPage, renamePage, addPage, removePage } = useBuilder();
  return <section className="space-y-3">
    <div><p className="panel-title">页面导航</p><p className="mt-1 text-xs leading-5 text-slate-400">每个导航标题对应一个独立页面。</p></div>
    <div className="space-y-2">{pages.map((page) => <div key={page.id} className={`flex items-center gap-1.5 rounded border p-1.5 ${page.id === activePageId ? "border-sky-300 bg-sky-50" : "border-slate-200"}`}><button onClick={() => selectPage(page.id)} className={`h-8 w-7 shrink-0 rounded text-xs font-bold ${page.id === activePageId ? "text-sky-700" : "text-slate-400 hover:text-slate-700"}`} title="切换页面">{pages.indexOf(page) + 1}</button><input className="min-w-0 flex-1 bg-transparent px-1 text-xs font-semibold outline-none" value={page.title} onFocus={() => selectPage(page.id)} onChange={(event) => renamePage(page.id, event.target.value)} aria-label="导航标题" /><button disabled={pages.length <= 1} className="icon-button h-7 w-7 text-red-500" onClick={() => removePage(page.id)} title={pages.length <= 1 ? "至少保留一个页面" : "删除页面"}><Trash2 size={13} /></button></div>)}</div>
    <AddButton onClick={addPage}>添加页面</AddButton>
  </section>;
}

export function PropertiesPanel() {
  const { selectedModule, updateModule } = useBuilder();
  return <aside className="min-h-0 overflow-y-auto border-l border-slate-200 bg-white">
    <div className="sticky top-0 z-10 border-b border-slate-200 bg-white px-4 py-4"><p className="panel-title">属性设置</p>{selectedModule && <p className="mt-1 text-sm font-bold text-slate-800">{MODULE_META[selectedModule.type].label}</p>}</div>
    <div className="space-y-5 p-4"><StoreIdentity /><div className="border-t border-slate-200 pt-5"><PageNavigation /></div><div className="border-t border-slate-200 pt-5">{!selectedModule ? <div className="flex h-52 flex-col items-center justify-center px-4 text-center text-slate-400"><Settings2 size={24} strokeWidth={1.5} /><p className="mt-3 text-sm font-semibold text-slate-600">尚未选择模块</p><p className="mt-1 text-xs leading-5">在画布中选择一个模块，即可编辑内容。</p></div> : <div className="space-y-4"><p className="panel-title">模块内容</p><Editors module={selectedModule} update={(patch) => updateModule(selectedModule.id, patch)} /></div>}</div></div>
  </aside>;
}
